<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click-checkbox</name>
   <tag></tag>
   <elementGuidId>48f83dbd-0beb-48c7-95b3-a78b0feb7f9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/sec-view/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/sec-view/div/input</value>
      <webElementGuid>e7d8e101-dc6e-4831-bcf3-0a7ef336171f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
