<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>r-address</name>
   <tag></tag>
   <elementGuidId>b3b89907-ee5d-4313-944b-ba109a282a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[3]/div[2]/sec-view[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[3]/div[2]/sec-view[1]/div/input</value>
      <webElementGuid>e9b9f78e-dd63-420c-ae70-a7cf1478b512</webElementGuid>
   </webElementProperties>
</WebElementEntity>
