<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>r-lname</name>
   <tag></tag>
   <elementGuidId>b7a1be00-a7e6-4e64-b709-f6a7b0d41e1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[2]/div[1]/sec-view[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[2]/div[1]/sec-view[2]/div/input</value>
      <webElementGuid>b5a62293-cc8d-4ba2-b940-af183e5f81a6</webElementGuid>
   </webElementProperties>
</WebElementEntity>
