<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>r-password</name>
   <tag></tag>
   <elementGuidId>9b335c76-4dec-4d2e-a6b3-07fbc35d1f90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[1]/div[2]/sec-view[1]/div/input</value>
      <webElementGuid>09ead559-f306-4971-bbe7-e84c9bcbbcf4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
