<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>r-postal</name>
   <tag></tag>
   <elementGuidId>d96155f2-82c2-4d07-8dcd-b4bb131dcda5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[3]/div[3]/sec-view/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[3]/div[3]/sec-view/div/input</value>
      <webElementGuid>f3db7a46-7300-4774-8e16-0ed983c58b89</webElementGuid>
   </webElementProperties>
</WebElementEntity>
