<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>r-region</name>
   <tag></tag>
   <elementGuidId>6dfcca9c-7adf-460d-8589-db395e183f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;formCover&quot;]/div[3]/div[2]/sec-view[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;formCover&quot;]/div[3]/div[2]/sec-view[2]/div/input</value>
      <webElementGuid>eb8d1da7-96ef-4014-94f2-a6588908aa97</webElementGuid>
   </webElementProperties>
</WebElementEntity>
