<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cont-shop</name>
   <tag></tag>
   <elementGuidId>7aa82df9-e370-4d12-903c-3e0d01505f5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;shoppingCart&quot;]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;shoppingCart&quot;]/div/a</value>
      <webElementGuid>90571163-49c8-4b03-8879-36618c5ad7d3</webElementGuid>
   </webElementProperties>
</WebElementEntity>
