<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>password-pay</name>
   <tag></tag>
   <elementGuidId>435ddd82-47a7-4e78-b5f6-d8749883e462</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentMethod&quot;]/div/div[2]/sec-form/sec-view[2]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentMethod&quot;]/div/div[2]/sec-form/sec-view[2]/div/input</value>
      <webElementGuid>a5bf4140-2dff-477b-b934-fd1eabf1b02f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
