<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>username-pay</name>
   <tag></tag>
   <elementGuidId>5868064e-3b2c-494d-b030-a016f54dcc1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;paymentMethod&quot;]/div/div[2]/sec-form/sec-view[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;paymentMethod&quot;]/div/div[2]/sec-form/sec-view[1]/div/input</value>
      <webElementGuid>be7edcdc-5da0-4b6a-a079-c2e1f786820e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
