<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>speaker-detail</name>
   <tag></tag>
   <elementGuidId>d0352d80-ee7b-4097-9121-97b813a80ea4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/section/article/div[3]/div/div/div[2]/ul/li[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/section/article/div[3]/div/div/div[2]/ul/li[1]</value>
      <webElementGuid>ce419272-3104-447a-bf40-15e9e88f87db</webElementGuid>
   </webElementProperties>
</WebElementEntity>
